"""Migración inicial con modelos refactorizados

Revision ID: 86122ffdc6ce
Revises: 
Create Date: 2025-10-09 15:04:53.283587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86122ffdc6ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credenciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=True),
    sa.Column('contraseña', sa.String(length=100), nullable=True),
    sa.Column('actualizado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('semana', sa.Integer(), nullable=True),
    sa.Column('almuerzo', sa.Integer(), nullable=True),
    sa.Column('cena', sa.Integer(), nullable=True),
    sa.Column('feriado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('fecha')
    )
    op.create_table('entregas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('entregado_almuerzo', sa.Integer(), nullable=True),
    sa.Column('entregado_cena', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fecha'], ['pedidos.fecha'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entregas')
    op.drop_table('pedidos')
    op.drop_table('pagos')
    op.drop_table('log')
    op.drop_table('credenciales')
    # ### end Alembic commands ###
