"""Agrega campos de texto al modelo Pedido

Revision ID: fd317ed7ec0e
Revises: 86122ffdc6ce
Create Date: 2025-10-09 17:21:21.264152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd317ed7ec0e'
down_revision = '86122ffdc6ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrada', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fondo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('plato_cena', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('observaciones')
        batch_op.drop_column('plato_cena')
        batch_op.drop_column('fondo')
        batch_op.drop_column('entrada')

    # ### end Alembic commands ###
